// Mocks generated by Mockito 5.4.4 from annotations
// in GitaWisdom/test/services/progressive_cache_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:GitaWisdom/models/chapter.dart' as _i7;
import 'package:GitaWisdom/models/chapter_summary.dart' as _i6;
import 'package:GitaWisdom/models/journal_entry.dart' as _i9;
import 'package:GitaWisdom/models/scenario.dart' as _i8;
import 'package:GitaWisdom/models/verse.dart' as _i3;
import 'package:GitaWisdom/services/enhanced_supabase_service.dart' as _i4;
import 'package:hive/hive.dart' as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;
import 'package:supabase_flutter/supabase_flutter.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSupabaseClient_0 extends _i1.SmartFake
    implements _i2.SupabaseClient {
  _FakeSupabaseClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVerse_1 extends _i1.SmartFake implements _i3.Verse {
  _FakeVerse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [EnhancedSupabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockEnhancedSupabaseService extends _i1.Mock
    implements _i4.EnhancedSupabaseService {
  MockEnhancedSupabaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SupabaseClient get client => (super.noSuchMethod(
        Invocation.getter(#client),
        returnValue: _FakeSupabaseClient_0(
          this,
          Invocation.getter(#client),
        ),
      ) as _i2.SupabaseClient);

  @override
  _i5.Future<bool> testConnection() => (super.noSuchMethod(
        Invocation.method(
          #testConnection,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> initializeLanguages() => (super.noSuchMethod(
        Invocation.method(
          #initializeLanguages,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setCurrentLanguage(String? langCode) => (super.noSuchMethod(
        Invocation.method(
          #setCurrentLanguage,
          [langCode],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i6.ChapterSummary>> fetchChapterSummaries(
          [String? langCode]) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchChapterSummaries,
          [langCode],
        ),
        returnValue:
            _i5.Future<List<_i6.ChapterSummary>>.value(<_i6.ChapterSummary>[]),
      ) as _i5.Future<List<_i6.ChapterSummary>>);

  @override
  _i5.Future<_i7.Chapter?> fetchChapterById(
    int? chapterId, [
    String? langCode,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchChapterById,
          [
            chapterId,
            langCode,
          ],
        ),
        returnValue: _i5.Future<_i7.Chapter?>.value(),
      ) as _i5.Future<_i7.Chapter?>);

  @override
  _i5.Future<List<_i7.Chapter>> fetchAllChapters([String? langCode]) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchAllChapters,
          [langCode],
        ),
        returnValue: _i5.Future<List<_i7.Chapter>>.value(<_i7.Chapter>[]),
      ) as _i5.Future<List<_i7.Chapter>>);

  @override
  _i5.Future<List<_i8.Scenario>> fetchScenariosByChapter(
    int? chapterId, [
    String? langCode,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchScenariosByChapter,
          [
            chapterId,
            langCode,
          ],
        ),
        returnValue: _i5.Future<List<_i8.Scenario>>.value(<_i8.Scenario>[]),
      ) as _i5.Future<List<_i8.Scenario>>);

  @override
  _i5.Future<_i8.Scenario?> fetchScenarioById(
    int? scenarioId, [
    String? langCode,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchScenarioById,
          [
            scenarioId,
            langCode,
          ],
        ),
        returnValue: _i5.Future<_i8.Scenario?>.value(),
      ) as _i5.Future<_i8.Scenario?>);

  @override
  _i5.Future<List<_i8.Scenario>> searchScenarios(
    String? query, [
    String? langCode,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchScenarios,
          [
            query,
            langCode,
          ],
        ),
        returnValue: _i5.Future<List<_i8.Scenario>>.value(<_i8.Scenario>[]),
      ) as _i5.Future<List<_i8.Scenario>>);

  @override
  _i5.Future<List<_i8.Scenario>> fetchScenarios({
    int? limit = 2000,
    int? offset = 0,
    String? langCode,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchScenarios,
          [],
          {
            #limit: limit,
            #offset: offset,
            #langCode: langCode,
          },
        ),
        returnValue: _i5.Future<List<_i8.Scenario>>.value(<_i8.Scenario>[]),
      ) as _i5.Future<List<_i8.Scenario>>);

  @override
  _i5.Future<int> getScenarioCount() => (super.noSuchMethod(
        Invocation.method(
          #getScenarioCount,
          [],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<List<_i3.Verse>> fetchVersesByChapter(
    int? chapterId, [
    String? langCode,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchVersesByChapter,
          [
            chapterId,
            langCode,
          ],
        ),
        returnValue: _i5.Future<List<_i3.Verse>>.value(<_i3.Verse>[]),
      ) as _i5.Future<List<_i3.Verse>>);

  @override
  _i5.Future<_i3.Verse> fetchRandomVerseByChapter(
    int? chapterId, [
    String? langCode,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchRandomVerseByChapter,
          [
            chapterId,
            langCode,
          ],
        ),
        returnValue: _i5.Future<_i3.Verse>.value(_FakeVerse_1(
          this,
          Invocation.method(
            #fetchRandomVerseByChapter,
            [
              chapterId,
              langCode,
            ],
          ),
        )),
      ) as _i5.Future<_i3.Verse>);

  @override
  _i5.Future<_i8.Scenario?> fetchRandomScenario() => (super.noSuchMethod(
        Invocation.method(
          #fetchRandomScenario,
          [],
        ),
        returnValue: _i5.Future<_i8.Scenario?>.value(),
      ) as _i5.Future<_i8.Scenario?>);

  @override
  _i5.Future<int> fetchScenarioCount(int? chapterId) => (super.noSuchMethod(
        Invocation.method(
          #fetchScenarioCount,
          [chapterId],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<void> insertJournalEntry(_i9.JournalEntry? entry) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertJournalEntry,
          [entry],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteJournalEntry(String? entryId) => (super.noSuchMethod(
        Invocation.method(
          #deleteJournalEntry,
          [entryId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i9.JournalEntry>> fetchJournalEntries() =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchJournalEntries,
          [],
        ),
        returnValue:
            _i5.Future<List<_i9.JournalEntry>>.value(<_i9.JournalEntry>[]),
      ) as _i5.Future<List<_i9.JournalEntry>>);

  @override
  _i5.Future<void> insertFavorite(String? scenarioTitle) => (super.noSuchMethod(
        Invocation.method(
          #insertFavorite,
          [scenarioTitle],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> removeFavorite(String? scenarioTitle) => (super.noSuchMethod(
        Invocation.method(
          #removeFavorite,
          [scenarioTitle],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<String>> fetchFavorites() => (super.noSuchMethod(
        Invocation.method(
          #fetchFavorites,
          [],
        ),
        returnValue: _i5.Future<List<String>>.value(<String>[]),
      ) as _i5.Future<List<String>>);

  @override
  _i5.Future<Map<String, dynamic>> getTranslationCoverage([String? langCode]) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTranslationCoverage,
          [langCode],
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<bool> refreshTranslationViews() => (super.noSuchMethod(
        Invocation.method(
          #refreshTranslationViews,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  bool isLanguageSupported(String? langCode) => (super.noSuchMethod(
        Invocation.method(
          #isLanguageSupported,
          [langCode],
        ),
        returnValue: false,
      ) as bool);

  @override
  String getLanguageDisplayName(
    String? langCode, {
    bool? useNative = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLanguageDisplayName,
          [langCode],
          {#useNative: useNative},
        ),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.method(
            #getLanguageDisplayName,
            [langCode],
            {#useNative: useNative},
          ),
        ),
      ) as String);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [Box].
///
/// See the documentation for Mockito's code generation for more information.
class MockBox<E> extends _i1.Mock implements _i11.Box<E> {
  MockBox() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Iterable<E> get values => (super.noSuchMethod(
        Invocation.getter(#values),
        returnValue: <E>[],
      ) as Iterable<E>);

  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
      ) as String);

  @override
  bool get isOpen => (super.noSuchMethod(
        Invocation.getter(#isOpen),
        returnValue: false,
      ) as bool);

  @override
  bool get lazy => (super.noSuchMethod(
        Invocation.getter(#lazy),
        returnValue: false,
      ) as bool);

  @override
  Iterable<dynamic> get keys => (super.noSuchMethod(
        Invocation.getter(#keys),
        returnValue: <dynamic>[],
      ) as Iterable<dynamic>);

  @override
  int get length => (super.noSuchMethod(
        Invocation.getter(#length),
        returnValue: 0,
      ) as int);

  @override
  bool get isEmpty => (super.noSuchMethod(
        Invocation.getter(#isEmpty),
        returnValue: false,
      ) as bool);

  @override
  bool get isNotEmpty => (super.noSuchMethod(
        Invocation.getter(#isNotEmpty),
        returnValue: false,
      ) as bool);

  @override
  Iterable<E> valuesBetween({
    dynamic startKey,
    dynamic endKey,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #valuesBetween,
          [],
          {
            #startKey: startKey,
            #endKey: endKey,
          },
        ),
        returnValue: <E>[],
      ) as Iterable<E>);

  @override
  E? getAt(int? index) => (super.noSuchMethod(Invocation.method(
        #getAt,
        [index],
      )) as E?);

  @override
  Map<dynamic, E> toMap() => (super.noSuchMethod(
        Invocation.method(
          #toMap,
          [],
        ),
        returnValue: <dynamic, E>{},
      ) as Map<dynamic, E>);

  @override
  dynamic keyAt(int? index) => super.noSuchMethod(Invocation.method(
        #keyAt,
        [index],
      ));

  @override
  _i5.Stream<_i11.BoxEvent> watch({dynamic key}) => (super.noSuchMethod(
        Invocation.method(
          #watch,
          [],
          {#key: key},
        ),
        returnValue: _i5.Stream<_i11.BoxEvent>.empty(),
      ) as _i5.Stream<_i11.BoxEvent>);

  @override
  bool containsKey(dynamic key) => (super.noSuchMethod(
        Invocation.method(
          #containsKey,
          [key],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> put(
    dynamic key,
    E? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [
            key,
            value,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> putAt(
    int? index,
    E? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #putAt,
          [
            index,
            value,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> putAll(Map<dynamic, E>? entries) => (super.noSuchMethod(
        Invocation.method(
          #putAll,
          [entries],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<int> add(E? value) => (super.noSuchMethod(
        Invocation.method(
          #add,
          [value],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<Iterable<int>> addAll(Iterable<E>? values) => (super.noSuchMethod(
        Invocation.method(
          #addAll,
          [values],
        ),
        returnValue: _i5.Future<Iterable<int>>.value(<int>[]),
      ) as _i5.Future<Iterable<int>>);

  @override
  _i5.Future<void> delete(dynamic key) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [key],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteAt(int? index) => (super.noSuchMethod(
        Invocation.method(
          #deleteAt,
          [index],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteAll(Iterable<dynamic>? keys) => (super.noSuchMethod(
        Invocation.method(
          #deleteAll,
          [keys],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> compact() => (super.noSuchMethod(
        Invocation.method(
          #compact,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<int> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteFromDisk() => (super.noSuchMethod(
        Invocation.method(
          #deleteFromDisk,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> flush() => (super.noSuchMethod(
        Invocation.method(
          #flush,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
