// Mocks generated by Mockito 5.4.4 from annotations
// in GitaWisdom/test/services/progressive_scenario_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:ui' as _i6;

import 'package:flutter/services.dart' as _i7;
import 'package:flutter/widgets.dart' as _i8;
import 'package:GitaWisdom/models/scenario.dart' as _i4;
import 'package:GitaWisdom/services/intelligent_caching_service.dart' as _i2;
import 'package:GitaWisdom/services/progressive_cache_service.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [IntelligentCachingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIntelligentCachingService extends _i1.Mock
    implements _i2.IntelligentCachingService {
  MockIntelligentCachingService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get hasCriticalScenarios => (super.noSuchMethod(
        Invocation.getter(#hasCriticalScenarios),
        returnValue: false,
      ) as bool);

  @override
  _i3.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> waitForCriticalScenarios() => (super.noSuchMethod(
        Invocation.method(
          #waitForCriticalScenarios,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.Scenario>> getScenariosByLevel(_i5.CacheLevel? level) =>
      (super.noSuchMethod(
        Invocation.method(
          #getScenariosByLevel,
          [level],
        ),
        returnValue: _i3.Future<List<_i4.Scenario>>.value(<_i4.Scenario>[]),
      ) as _i3.Future<List<_i4.Scenario>>);

  @override
  _i3.Future<_i4.Scenario?> getScenario(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getScenario,
          [id],
        ),
        returnValue: _i3.Future<_i4.Scenario?>.value(),
      ) as _i3.Future<_i4.Scenario?>);

  @override
  List<_i4.Scenario> getCriticalScenariosSync() => (super.noSuchMethod(
        Invocation.method(
          #getCriticalScenariosSync,
          [],
        ),
        returnValue: <_i4.Scenario>[],
      ) as List<_i4.Scenario>);

  @override
  _i3.Future<Map<int, int>> getScenarioCountsByChapter() => (super.noSuchMethod(
        Invocation.method(
          #getScenarioCountsByChapter,
          [],
        ),
        returnValue: _i3.Future<Map<int, int>>.value(<int, int>{}),
      ) as _i3.Future<Map<int, int>>);

  @override
  _i3.Future<List<_i4.Scenario>> searchScenarios(
    String? query, {
    int? maxResults,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchScenarios,
          [query],
          {#maxResults: maxResults},
        ),
        returnValue: _i3.Future<List<_i4.Scenario>>.value(<_i4.Scenario>[]),
      ) as _i3.Future<List<_i4.Scenario>>);

  @override
  Map<String, dynamic> getProgress() => (super.noSuchMethod(
        Invocation.method(
          #getProgress,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i3.Future<void> refreshFromServer() => (super.noSuchMethod(
        Invocation.method(
          #refreshFromServer,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  void didChangeAppLifecycleState(_i6.AppLifecycleState? state) =>
      super.noSuchMethod(
        Invocation.method(
          #didChangeAppLifecycleState,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<bool> didPopRoute() => (super.noSuchMethod(
        Invocation.method(
          #didPopRoute,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  bool handleStartBackGesture(_i7.PredictiveBackEvent? backEvent) =>
      (super.noSuchMethod(
        Invocation.method(
          #handleStartBackGesture,
          [backEvent],
        ),
        returnValue: false,
      ) as bool);

  @override
  void handleUpdateBackGestureProgress(_i7.PredictiveBackEvent? backEvent) =>
      super.noSuchMethod(
        Invocation.method(
          #handleUpdateBackGestureProgress,
          [backEvent],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void handleCommitBackGesture() => super.noSuchMethod(
        Invocation.method(
          #handleCommitBackGesture,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void handleCancelBackGesture() => super.noSuchMethod(
        Invocation.method(
          #handleCancelBackGesture,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<bool> didPushRoute(String? route) => (super.noSuchMethod(
        Invocation.method(
          #didPushRoute,
          [route],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> didPushRouteInformation(
          _i8.RouteInformation? routeInformation) =>
      (super.noSuchMethod(
        Invocation.method(
          #didPushRouteInformation,
          [routeInformation],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  void didChangeMetrics() => super.noSuchMethod(
        Invocation.method(
          #didChangeMetrics,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didChangeTextScaleFactor() => super.noSuchMethod(
        Invocation.method(
          #didChangeTextScaleFactor,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didChangePlatformBrightness() => super.noSuchMethod(
        Invocation.method(
          #didChangePlatformBrightness,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didChangeLocales(List<_i6.Locale>? locales) => super.noSuchMethod(
        Invocation.method(
          #didChangeLocales,
          [locales],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didChangeViewFocus(_i6.ViewFocusEvent? event) => super.noSuchMethod(
        Invocation.method(
          #didChangeViewFocus,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<_i6.AppExitResponse> didRequestAppExit() => (super.noSuchMethod(
        Invocation.method(
          #didRequestAppExit,
          [],
        ),
        returnValue:
            _i3.Future<_i6.AppExitResponse>.value(_i6.AppExitResponse.exit),
      ) as _i3.Future<_i6.AppExitResponse>);

  @override
  void didHaveMemoryPressure() => super.noSuchMethod(
        Invocation.method(
          #didHaveMemoryPressure,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didChangeAccessibilityFeatures() => super.noSuchMethod(
        Invocation.method(
          #didChangeAccessibilityFeatures,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
