// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
/*
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjhaN9NM7kQ1TwwOZTW0FBULBdW5hUq9M',
    appId: '1:315365731796:web:cc53ba95ff7eb01dce7a41',
    messagingSenderId: '315365731796',
    projectId: 'oldwisdom-2b2da',
    authDomain: 'oldwisdom-2b2da.firebaseapp.com',
    storageBucket: 'oldwisdom-2b2da.firebasestorage.app',
    measurementId: 'G-146NSYJMEX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA92WrqZ3GVAV8tmCwgUgjFe5gXYpFG5ew',
    appId: '1:315365731796:android:44612fc8efc2b0fece7a41',
    messagingSenderId: '315365731796',
    projectId: 'oldwisdom-2b2da',
    storageBucket: 'oldwisdom-2b2da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM23Jzq8_ZnrHWTl1akNJoHifSfML3API',
    appId: '1:315365731796:ios:8208da6143138cb3ce7a41',
    messagingSenderId: '315365731796',
    projectId: 'oldwisdom-2b2da',
    storageBucket: 'oldwisdom-2b2da.firebasestorage.app',
    iosBundleId: 'com.example.oldwisdom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBM23Jzq8_ZnrHWTl1akNJoHifSfML3API',
    appId: '1:315365731796:ios:8208da6143138cb3ce7a41',
    messagingSenderId: '315365731796',
    projectId: 'oldwisdom-2b2da',
    storageBucket: 'oldwisdom-2b2da.firebasestorage.app',
    iosBundleId: 'com.example.oldwisdom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjhaN9NM7kQ1TwwOZTW0FBULBdW5hUq9M',
    appId: '1:315365731796:web:49ffbd52bf5e4c81ce7a41',
    messagingSenderId: '315365731796',
    projectId: 'oldwisdom-2b2da',
    authDomain: 'oldwisdom-2b2da.firebaseapp.com',
    storageBucket: 'oldwisdom-2b2da.firebasestorage.app',
    measurementId: 'G-H8V3C6EHDR',
  );
}
*/
