// Mocks generated by Mockito 5.4.4 from annotations
// in GitaWisdom/test/screens/home_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:ui' as _i8;

import 'package:flutter/material.dart' as _i10;
import 'package:GitaWisdom/models/chapter.dart' as _i13;
import 'package:GitaWisdom/models/chapter_summary.dart' as _i12;
import 'package:GitaWisdom/models/journal_entry.dart' as _i15;
import 'package:GitaWisdom/models/scenario.dart' as _i14;
import 'package:GitaWisdom/models/verse.dart' as _i4;
import 'package:GitaWisdom/services/enhanced_supabase_service.dart' as _i11;
import 'package:GitaWisdom/services/settings_service.dart' as _i9;
import 'package:GitaWisdom/services/supabase_auth_service.dart' as _i5;
import 'package:hive/hive.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:supabase_flutter/supabase_flutter.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBox_0<E> extends _i1.SmartFake implements _i2.Box<E> {
  _FakeBox_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSupabaseClient_1 extends _i1.SmartFake
    implements _i3.SupabaseClient {
  _FakeSupabaseClient_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVerse_2 extends _i1.SmartFake implements _i4.Verse {
  _FakeVerse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SupabaseAuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupabaseAuthService extends _i1.Mock
    implements _i5.SupabaseAuthService {
  MockSupabaseAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isAuthenticated => (super.noSuchMethod(
        Invocation.getter(#isAuthenticated),
        returnValue: false,
      ) as bool);

  @override
  bool get isAnonymous => (super.noSuchMethod(
        Invocation.getter(#isAnonymous),
        returnValue: false,
      ) as bool);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  String get databaseUserId => (super.noSuchMethod(
        Invocation.getter(#databaseUserId),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#databaseUserId),
        ),
      ) as String);

  @override
  _i7.Stream<bool> get authStateChanges => (super.noSuchMethod(
        Invocation.getter(#authStateChanges),
        returnValue: _i7.Stream<bool>.empty(),
      ) as _i7.Stream<bool>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i7.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<bool> signUpWithEmail(
    String? email,
    String? password,
    String? name,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUpWithEmail,
          [
            email,
            password,
            name,
          ],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> signInWithEmail(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithEmail,
          [
            email,
            password,
          ],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> signInAnonymously() => (super.noSuchMethod(
        Invocation.method(
          #signInAnonymously,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<bool> resetPassword(String? email) => (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [email],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> updatePassword(String? newPassword) => (super.noSuchMethod(
        Invocation.method(
          #updatePassword,
          [newPassword],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> verifyOTP(
    String? email,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyOTP,
          [
            email,
            token,
          ],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> deleteAccount() => (super.noSuchMethod(
        Invocation.method(
          #deleteAccount,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> checkUserExists(String? email) => (super.noSuchMethod(
        Invocation.method(
          #checkUserExists,
          [email],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  void clearError() => super.noSuchMethod(
        Invocation.method(
          #clearError,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<bool> continueAsAnonymous() => (super.noSuchMethod(
        Invocation.method(
          #continueAsAnonymous,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> signInWithGoogle() => (super.noSuchMethod(
        Invocation.method(
          #signInWithGoogle,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> signInWithApple() => (super.noSuchMethod(
        Invocation.method(
          #signInWithApple,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SettingsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsService extends _i1.Mock implements _i9.SettingsService {
  MockSettingsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Box<dynamic> get box => (super.noSuchMethod(
        Invocation.getter(#box),
        returnValue: _FakeBox_0<dynamic>(
          this,
          Invocation.getter(#box),
        ),
      ) as _i2.Box<dynamic>);

  @override
  bool get isDarkMode => (super.noSuchMethod(
        Invocation.getter(#isDarkMode),
        returnValue: false,
      ) as bool);

  @override
  set isDarkMode(bool? v) => super.noSuchMethod(
        Invocation.setter(
          #isDarkMode,
          v,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get language => (super.noSuchMethod(
        Invocation.getter(#language),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#language),
        ),
      ) as String);

  @override
  set language(String? v) => super.noSuchMethod(
        Invocation.setter(
          #language,
          v,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get fontSize => (super.noSuchMethod(
        Invocation.getter(#fontSize),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#fontSize),
        ),
      ) as String);

  @override
  set fontSize(String? v) => super.noSuchMethod(
        Invocation.setter(
          #fontSize,
          v,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.ThemeMode get themeMode => (super.noSuchMethod(
        Invocation.getter(#themeMode),
        returnValue: _i10.ThemeMode.system,
      ) as _i10.ThemeMode);

  @override
  bool get musicEnabled => (super.noSuchMethod(
        Invocation.getter(#musicEnabled),
        returnValue: false,
      ) as bool);

  @override
  set musicEnabled(bool? v) => super.noSuchMethod(
        Invocation.setter(
          #musicEnabled,
          v,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get textShadowEnabled => (super.noSuchMethod(
        Invocation.getter(#textShadowEnabled),
        returnValue: false,
      ) as bool);

  @override
  set textShadowEnabled(bool? v) => super.noSuchMethod(
        Invocation.setter(
          #textShadowEnabled,
          v,
        ),
        returnValueForMissingStub: null,
      );

  @override
  double get backgroundOpacity => (super.noSuchMethod(
        Invocation.getter(#backgroundOpacity),
        returnValue: 0.0,
      ) as double);

  @override
  set backgroundOpacity(double? v) => super.noSuchMethod(
        Invocation.setter(
          #backgroundOpacity,
          v,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setAppLanguage(String? langCode) => super.noSuchMethod(
        Invocation.method(
          #setAppLanguage,
          [langCode],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setTheme(_i10.ThemeMode? mode) => super.noSuchMethod(
        Invocation.method(
          #setTheme,
          [mode],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setFontSize(String? size) => super.noSuchMethod(
        Invocation.method(
          #setFontSize,
          [size],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [EnhancedSupabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockEnhancedSupabaseService extends _i1.Mock
    implements _i11.EnhancedSupabaseService {
  MockEnhancedSupabaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.SupabaseClient get client => (super.noSuchMethod(
        Invocation.getter(#client),
        returnValue: _FakeSupabaseClient_1(
          this,
          Invocation.getter(#client),
        ),
      ) as _i3.SupabaseClient);

  @override
  _i7.Future<bool> testConnection() => (super.noSuchMethod(
        Invocation.method(
          #testConnection,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<void> initializeLanguages() => (super.noSuchMethod(
        Invocation.method(
          #initializeLanguages,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> setCurrentLanguage(String? langCode) => (super.noSuchMethod(
        Invocation.method(
          #setCurrentLanguage,
          [langCode],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i12.ChapterSummary>> fetchChapterSummaries(
          [String? langCode]) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchChapterSummaries,
          [langCode],
        ),
        returnValue: _i7.Future<List<_i12.ChapterSummary>>.value(
            <_i12.ChapterSummary>[]),
      ) as _i7.Future<List<_i12.ChapterSummary>>);

  @override
  _i7.Future<_i13.Chapter?> fetchChapterById(
    int? chapterId, [
    String? langCode,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchChapterById,
          [
            chapterId,
            langCode,
          ],
        ),
        returnValue: _i7.Future<_i13.Chapter?>.value(),
      ) as _i7.Future<_i13.Chapter?>);

  @override
  _i7.Future<List<_i13.Chapter>> fetchAllChapters([String? langCode]) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchAllChapters,
          [langCode],
        ),
        returnValue: _i7.Future<List<_i13.Chapter>>.value(<_i13.Chapter>[]),
      ) as _i7.Future<List<_i13.Chapter>>);

  @override
  _i7.Future<List<_i14.Scenario>> fetchScenariosByChapter(
    int? chapterId, [
    String? langCode,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchScenariosByChapter,
          [
            chapterId,
            langCode,
          ],
        ),
        returnValue: _i7.Future<List<_i14.Scenario>>.value(<_i14.Scenario>[]),
      ) as _i7.Future<List<_i14.Scenario>>);

  @override
  _i7.Future<_i14.Scenario?> fetchScenarioById(
    int? scenarioId, [
    String? langCode,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchScenarioById,
          [
            scenarioId,
            langCode,
          ],
        ),
        returnValue: _i7.Future<_i14.Scenario?>.value(),
      ) as _i7.Future<_i14.Scenario?>);

  @override
  _i7.Future<List<_i14.Scenario>> searchScenarios(
    String? query, [
    String? langCode,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchScenarios,
          [
            query,
            langCode,
          ],
        ),
        returnValue: _i7.Future<List<_i14.Scenario>>.value(<_i14.Scenario>[]),
      ) as _i7.Future<List<_i14.Scenario>>);

  @override
  _i7.Future<List<_i14.Scenario>> fetchScenarios({
    int? limit = 2000,
    int? offset = 0,
    String? langCode,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchScenarios,
          [],
          {
            #limit: limit,
            #offset: offset,
            #langCode: langCode,
          },
        ),
        returnValue: _i7.Future<List<_i14.Scenario>>.value(<_i14.Scenario>[]),
      ) as _i7.Future<List<_i14.Scenario>>);

  @override
  _i7.Future<int> getScenarioCount() => (super.noSuchMethod(
        Invocation.method(
          #getScenarioCount,
          [],
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Future<List<_i4.Verse>> fetchVersesByChapter(
    int? chapterId, [
    String? langCode,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchVersesByChapter,
          [
            chapterId,
            langCode,
          ],
        ),
        returnValue: _i7.Future<List<_i4.Verse>>.value(<_i4.Verse>[]),
      ) as _i7.Future<List<_i4.Verse>>);

  @override
  _i7.Future<_i4.Verse> fetchRandomVerseByChapter(
    int? chapterId, [
    String? langCode,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchRandomVerseByChapter,
          [
            chapterId,
            langCode,
          ],
        ),
        returnValue: _i7.Future<_i4.Verse>.value(_FakeVerse_2(
          this,
          Invocation.method(
            #fetchRandomVerseByChapter,
            [
              chapterId,
              langCode,
            ],
          ),
        )),
      ) as _i7.Future<_i4.Verse>);

  @override
  _i7.Future<_i14.Scenario?> fetchRandomScenario() => (super.noSuchMethod(
        Invocation.method(
          #fetchRandomScenario,
          [],
        ),
        returnValue: _i7.Future<_i14.Scenario?>.value(),
      ) as _i7.Future<_i14.Scenario?>);

  @override
  _i7.Future<int> fetchScenarioCount(int? chapterId) => (super.noSuchMethod(
        Invocation.method(
          #fetchScenarioCount,
          [chapterId],
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Future<void> insertJournalEntry(_i15.JournalEntry? entry) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertJournalEntry,
          [entry],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> deleteJournalEntry(String? entryId) => (super.noSuchMethod(
        Invocation.method(
          #deleteJournalEntry,
          [entryId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i15.JournalEntry>> fetchJournalEntries() =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchJournalEntries,
          [],
        ),
        returnValue:
            _i7.Future<List<_i15.JournalEntry>>.value(<_i15.JournalEntry>[]),
      ) as _i7.Future<List<_i15.JournalEntry>>);

  @override
  _i7.Future<void> insertFavorite(String? scenarioTitle) => (super.noSuchMethod(
        Invocation.method(
          #insertFavorite,
          [scenarioTitle],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> removeFavorite(String? scenarioTitle) => (super.noSuchMethod(
        Invocation.method(
          #removeFavorite,
          [scenarioTitle],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<String>> fetchFavorites() => (super.noSuchMethod(
        Invocation.method(
          #fetchFavorites,
          [],
        ),
        returnValue: _i7.Future<List<String>>.value(<String>[]),
      ) as _i7.Future<List<String>>);

  @override
  _i7.Future<Map<String, dynamic>> getTranslationCoverage([String? langCode]) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTranslationCoverage,
          [langCode],
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<bool> refreshTranslationViews() => (super.noSuchMethod(
        Invocation.method(
          #refreshTranslationViews,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  bool isLanguageSupported(String? langCode) => (super.noSuchMethod(
        Invocation.method(
          #isLanguageSupported,
          [langCode],
        ),
        returnValue: false,
      ) as bool);

  @override
  String getLanguageDisplayName(
    String? langCode, {
    bool? useNative = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLanguageDisplayName,
          [langCode],
          {#useNative: useNative},
        ),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #getLanguageDisplayName,
            [langCode],
            {#useNative: useNative},
          ),
        ),
      ) as String);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
