// Mocks generated by Mockito 5.4.4 from annotations
// in GitaWisdom/test/screens/home_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;
import 'dart:ui' as _i10;

import 'package:flutter/foundation.dart' as _i6;
import 'package:flutter/material.dart' as _i5;
import 'package:GitaWisdom/core/theme/theme_provider.dart' as _i17;
import 'package:GitaWisdom/models/chapter.dart' as _i14;
import 'package:GitaWisdom/models/chapter_summary.dart' as _i13;
import 'package:GitaWisdom/models/journal_entry.dart' as _i16;
import 'package:GitaWisdom/models/scenario.dart' as _i15;
import 'package:GitaWisdom/models/verse.dart' as _i4;
import 'package:GitaWisdom/services/enhanced_supabase_service.dart' as _i12;
import 'package:GitaWisdom/services/settings_service.dart' as _i11;
import 'package:GitaWisdom/services/supabase_auth_service.dart' as _i7;
import 'package:hive/hive.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:supabase_flutter/supabase_flutter.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBox_0<E> extends _i1.SmartFake implements _i2.Box<E> {
  _FakeBox_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSupabaseClient_1 extends _i1.SmartFake
    implements _i3.SupabaseClient {
  _FakeSupabaseClient_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVerse_2 extends _i1.SmartFake implements _i4.Verse {
  _FakeVerse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeThemeData_3 extends _i1.SmartFake implements _i5.ThemeData {
  _FakeThemeData_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i6.DiagnosticLevel? minLevel = _i6.DiagnosticLevel.info}) =>
      super.toString();
}

/// A class which mocks [SupabaseAuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupabaseAuthService extends _i1.Mock
    implements _i7.SupabaseAuthService {
  MockSupabaseAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isAuthenticated => (super.noSuchMethod(
        Invocation.getter(#isAuthenticated),
        returnValue: false,
      ) as bool);

  @override
  bool get isAnonymous => (super.noSuchMethod(
        Invocation.getter(#isAnonymous),
        returnValue: false,
      ) as bool);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  String get databaseUserId => (super.noSuchMethod(
        Invocation.getter(#databaseUserId),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#databaseUserId),
        ),
      ) as String);

  @override
  _i9.Stream<bool> get authStateChanges => (super.noSuchMethod(
        Invocation.getter(#authStateChanges),
        returnValue: _i9.Stream<bool>.empty(),
      ) as _i9.Stream<bool>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i9.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<bool> signUpWithEmail(
    String? email,
    String? password,
    String? name,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUpWithEmail,
          [
            email,
            password,
            name,
          ],
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<bool> signInWithEmail(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithEmail,
          [
            email,
            password,
          ],
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<bool> signInAnonymously() => (super.noSuchMethod(
        Invocation.method(
          #signInAnonymously,
          [],
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<bool> resetPassword(String? email) => (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [email],
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<bool> updatePassword(String? newPassword) => (super.noSuchMethod(
        Invocation.method(
          #updatePassword,
          [newPassword],
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<bool> verifyOTP(
    String? email,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyOTP,
          [
            email,
            token,
          ],
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<bool> deleteAccount() => (super.noSuchMethod(
        Invocation.method(
          #deleteAccount,
          [],
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<bool> checkUserExists(String? email) => (super.noSuchMethod(
        Invocation.method(
          #checkUserExists,
          [email],
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  void clearError() => super.noSuchMethod(
        Invocation.method(
          #clearError,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<bool> continueAsAnonymous() => (super.noSuchMethod(
        Invocation.method(
          #continueAsAnonymous,
          [],
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<bool> signInWithGoogle() => (super.noSuchMethod(
        Invocation.method(
          #signInWithGoogle,
          [],
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<bool> signInWithApple() => (super.noSuchMethod(
        Invocation.method(
          #signInWithApple,
          [],
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i10.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i10.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SettingsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsService extends _i1.Mock implements _i11.SettingsService {
  MockSettingsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Box<dynamic> get box => (super.noSuchMethod(
        Invocation.getter(#box),
        returnValue: _FakeBox_0<dynamic>(
          this,
          Invocation.getter(#box),
        ),
      ) as _i2.Box<dynamic>);

  @override
  bool get isDarkMode => (super.noSuchMethod(
        Invocation.getter(#isDarkMode),
        returnValue: false,
      ) as bool);

  @override
  set isDarkMode(bool? v) => super.noSuchMethod(
        Invocation.setter(
          #isDarkMode,
          v,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get language => (super.noSuchMethod(
        Invocation.getter(#language),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#language),
        ),
      ) as String);

  @override
  set language(String? v) => super.noSuchMethod(
        Invocation.setter(
          #language,
          v,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get fontSize => (super.noSuchMethod(
        Invocation.getter(#fontSize),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#fontSize),
        ),
      ) as String);

  @override
  set fontSize(String? v) => super.noSuchMethod(
        Invocation.setter(
          #fontSize,
          v,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.ThemeMode get themeMode => (super.noSuchMethod(
        Invocation.getter(#themeMode),
        returnValue: _i5.ThemeMode.system,
      ) as _i5.ThemeMode);

  @override
  bool get musicEnabled => (super.noSuchMethod(
        Invocation.getter(#musicEnabled),
        returnValue: false,
      ) as bool);

  @override
  set musicEnabled(bool? v) => super.noSuchMethod(
        Invocation.setter(
          #musicEnabled,
          v,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get textShadowEnabled => (super.noSuchMethod(
        Invocation.getter(#textShadowEnabled),
        returnValue: false,
      ) as bool);

  @override
  set textShadowEnabled(bool? v) => super.noSuchMethod(
        Invocation.setter(
          #textShadowEnabled,
          v,
        ),
        returnValueForMissingStub: null,
      );

  @override
  double get backgroundOpacity => (super.noSuchMethod(
        Invocation.getter(#backgroundOpacity),
        returnValue: 0.0,
      ) as double);

  @override
  set backgroundOpacity(double? v) => super.noSuchMethod(
        Invocation.setter(
          #backgroundOpacity,
          v,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get canRefreshCache => (super.noSuchMethod(
        Invocation.getter(#canRefreshCache),
        returnValue: false,
      ) as bool);

  @override
  int get daysUntilNextRefresh => (super.noSuchMethod(
        Invocation.getter(#daysUntilNextRefresh),
        returnValue: 0,
      ) as int);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setAppLanguage(String? langCode) => super.noSuchMethod(
        Invocation.method(
          #setAppLanguage,
          [langCode],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setTheme(_i5.ThemeMode? mode) => super.noSuchMethod(
        Invocation.method(
          #setTheme,
          [mode],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setFontSize(String? size) => super.noSuchMethod(
        Invocation.method(
          #setFontSize,
          [size],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setLastCacheRefreshDate(DateTime? date) => super.noSuchMethod(
        Invocation.method(
          #setLastCacheRefreshDate,
          [date],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i10.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i10.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [EnhancedSupabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockEnhancedSupabaseService extends _i1.Mock
    implements _i12.EnhancedSupabaseService {
  MockEnhancedSupabaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.SupabaseClient get client => (super.noSuchMethod(
        Invocation.getter(#client),
        returnValue: _FakeSupabaseClient_1(
          this,
          Invocation.getter(#client),
        ),
      ) as _i3.SupabaseClient);

  @override
  _i9.Future<bool> testConnection() => (super.noSuchMethod(
        Invocation.method(
          #testConnection,
          [],
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<void> initializeLanguages() => (super.noSuchMethod(
        Invocation.method(
          #initializeLanguages,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> setCurrentLanguage(String? langCode) => (super.noSuchMethod(
        Invocation.method(
          #setCurrentLanguage,
          [langCode],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<List<_i13.ChapterSummary>> fetchChapterSummaries(
          [String? langCode]) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchChapterSummaries,
          [langCode],
        ),
        returnValue: _i9.Future<List<_i13.ChapterSummary>>.value(
            <_i13.ChapterSummary>[]),
      ) as _i9.Future<List<_i13.ChapterSummary>>);

  @override
  _i9.Future<_i14.Chapter?> fetchChapterById(
    int? chapterId, [
    String? langCode,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchChapterById,
          [
            chapterId,
            langCode,
          ],
        ),
        returnValue: _i9.Future<_i14.Chapter?>.value(),
      ) as _i9.Future<_i14.Chapter?>);

  @override
  _i9.Future<List<_i14.Chapter>> fetchAllChapters([String? langCode]) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchAllChapters,
          [langCode],
        ),
        returnValue: _i9.Future<List<_i14.Chapter>>.value(<_i14.Chapter>[]),
      ) as _i9.Future<List<_i14.Chapter>>);

  @override
  _i9.Future<List<_i15.Scenario>> fetchScenariosByChapter(
    int? chapterId, [
    String? langCode,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchScenariosByChapter,
          [
            chapterId,
            langCode,
          ],
        ),
        returnValue: _i9.Future<List<_i15.Scenario>>.value(<_i15.Scenario>[]),
      ) as _i9.Future<List<_i15.Scenario>>);

  @override
  _i9.Future<_i15.Scenario?> fetchScenarioById(
    int? scenarioId, [
    String? langCode,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchScenarioById,
          [
            scenarioId,
            langCode,
          ],
        ),
        returnValue: _i9.Future<_i15.Scenario?>.value(),
      ) as _i9.Future<_i15.Scenario?>);

  @override
  _i9.Future<List<_i15.Scenario>> searchScenarios(
    String? query, [
    String? langCode,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchScenarios,
          [
            query,
            langCode,
          ],
        ),
        returnValue: _i9.Future<List<_i15.Scenario>>.value(<_i15.Scenario>[]),
      ) as _i9.Future<List<_i15.Scenario>>);

  @override
  _i9.Future<List<_i15.Scenario>> fetchScenarios({
    int? limit = 2000,
    int? offset = 0,
    String? langCode,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchScenarios,
          [],
          {
            #limit: limit,
            #offset: offset,
            #langCode: langCode,
          },
        ),
        returnValue: _i9.Future<List<_i15.Scenario>>.value(<_i15.Scenario>[]),
      ) as _i9.Future<List<_i15.Scenario>>);

  @override
  _i9.Future<int> getScenarioCount() => (super.noSuchMethod(
        Invocation.method(
          #getScenarioCount,
          [],
        ),
        returnValue: _i9.Future<int>.value(0),
      ) as _i9.Future<int>);

  @override
  _i9.Future<List<_i4.Verse>> fetchVersesByChapter(
    int? chapterId, [
    String? langCode,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchVersesByChapter,
          [
            chapterId,
            langCode,
          ],
        ),
        returnValue: _i9.Future<List<_i4.Verse>>.value(<_i4.Verse>[]),
      ) as _i9.Future<List<_i4.Verse>>);

  @override
  _i9.Future<_i4.Verse> fetchRandomVerseByChapter(
    int? chapterId, [
    String? langCode,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchRandomVerseByChapter,
          [
            chapterId,
            langCode,
          ],
        ),
        returnValue: _i9.Future<_i4.Verse>.value(_FakeVerse_2(
          this,
          Invocation.method(
            #fetchRandomVerseByChapter,
            [
              chapterId,
              langCode,
            ],
          ),
        )),
      ) as _i9.Future<_i4.Verse>);

  @override
  _i9.Future<_i15.Scenario?> fetchRandomScenario() => (super.noSuchMethod(
        Invocation.method(
          #fetchRandomScenario,
          [],
        ),
        returnValue: _i9.Future<_i15.Scenario?>.value(),
      ) as _i9.Future<_i15.Scenario?>);

  @override
  _i9.Future<int> fetchScenarioCount(int? chapterId) => (super.noSuchMethod(
        Invocation.method(
          #fetchScenarioCount,
          [chapterId],
        ),
        returnValue: _i9.Future<int>.value(0),
      ) as _i9.Future<int>);

  @override
  _i9.Future<void> insertJournalEntry(_i16.JournalEntry? entry) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertJournalEntry,
          [entry],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> deleteJournalEntry(String? entryId) => (super.noSuchMethod(
        Invocation.method(
          #deleteJournalEntry,
          [entryId],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<List<_i16.JournalEntry>> fetchJournalEntries() =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchJournalEntries,
          [],
        ),
        returnValue:
            _i9.Future<List<_i16.JournalEntry>>.value(<_i16.JournalEntry>[]),
      ) as _i9.Future<List<_i16.JournalEntry>>);

  @override
  _i9.Future<void> insertFavorite(String? scenarioTitle) => (super.noSuchMethod(
        Invocation.method(
          #insertFavorite,
          [scenarioTitle],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> removeFavorite(String? scenarioTitle) => (super.noSuchMethod(
        Invocation.method(
          #removeFavorite,
          [scenarioTitle],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<List<String>> fetchFavorites() => (super.noSuchMethod(
        Invocation.method(
          #fetchFavorites,
          [],
        ),
        returnValue: _i9.Future<List<String>>.value(<String>[]),
      ) as _i9.Future<List<String>>);

  @override
  _i9.Future<Map<String, dynamic>> getTranslationCoverage([String? langCode]) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTranslationCoverage,
          [langCode],
        ),
        returnValue:
            _i9.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Future<bool> refreshTranslationViews() => (super.noSuchMethod(
        Invocation.method(
          #refreshTranslationViews,
          [],
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  bool isLanguageSupported(String? langCode) => (super.noSuchMethod(
        Invocation.method(
          #isLanguageSupported,
          [langCode],
        ),
        returnValue: false,
      ) as bool);

  @override
  String getLanguageDisplayName(
    String? langCode, {
    bool? useNative = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLanguageDisplayName,
          [langCode],
          {#useNative: useNative},
        ),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.method(
            #getLanguageDisplayName,
            [langCode],
            {#useNative: useNative},
          ),
        ),
      ) as String);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ThemeProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockThemeProvider extends _i1.Mock implements _i17.ThemeProvider {
  MockThemeProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isDark => (super.noSuchMethod(
        Invocation.getter(#isDark),
        returnValue: false,
      ) as bool);

  @override
  String get fontPref => (super.noSuchMethod(
        Invocation.getter(#fontPref),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#fontPref),
        ),
      ) as String);

  @override
  bool get shadowEnabled => (super.noSuchMethod(
        Invocation.getter(#shadowEnabled),
        returnValue: false,
      ) as bool);

  @override
  double get backgroundOpacity => (super.noSuchMethod(
        Invocation.getter(#backgroundOpacity),
        returnValue: 0.0,
      ) as double);

  @override
  double get textScale => (super.noSuchMethod(
        Invocation.getter(#textScale),
        returnValue: 0.0,
      ) as double);

  @override
  _i5.ThemeMode get themeMode => (super.noSuchMethod(
        Invocation.getter(#themeMode),
        returnValue: _i5.ThemeMode.system,
      ) as _i5.ThemeMode);

  @override
  _i5.ThemeData get lightTheme => (super.noSuchMethod(
        Invocation.getter(#lightTheme),
        returnValue: _FakeThemeData_3(
          this,
          Invocation.getter(#lightTheme),
        ),
      ) as _i5.ThemeData);

  @override
  _i5.ThemeData get darkTheme => (super.noSuchMethod(
        Invocation.getter(#darkTheme),
        returnValue: _FakeThemeData_3(
          this,
          Invocation.getter(#darkTheme),
        ),
      ) as _i5.ThemeData);

  @override
  _i5.ThemeData get currentTheme => (super.noSuchMethod(
        Invocation.getter(#currentTheme),
        returnValue: _FakeThemeData_3(
          this,
          Invocation.getter(#currentTheme),
        ),
      ) as _i5.ThemeData);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i9.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> updateTheme({
    bool? isDark,
    String? fontPref,
    bool? shadowEnabled,
    double? backgroundOpacity,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTheme,
          [],
          {
            #isDark: isDark,
            #fontPref: fontPref,
            #shadowEnabled: shadowEnabled,
            #backgroundOpacity: backgroundOpacity,
          },
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> toggleDarkMode() => (super.noSuchMethod(
        Invocation.method(
          #toggleDarkMode,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> setFontSize(String? size) => (super.noSuchMethod(
        Invocation.method(
          #setFontSize,
          [size],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> toggleShadow() => (super.noSuchMethod(
        Invocation.method(
          #toggleShadow,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> setBackgroundOpacity(double? opacity) => (super.noSuchMethod(
        Invocation.method(
          #setBackgroundOpacity,
          [opacity],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i10.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i10.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
