// Mocks generated by Mockito 5.4.4 from annotations
// in GitaWisdom/test/screens/journal_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:GitaWisdom/models/journal_entry.dart' as _i4;
import 'package:GitaWisdom/services/journal_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [JournalService].
///
/// See the documentation for Mockito's code generation for more information.
class MockJournalService extends _i1.Mock implements _i2.JournalService {
  MockJournalService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get totalEntries => (super.noSuchMethod(
        Invocation.getter(#totalEntries),
        returnValue: 0,
      ) as int);

  @override
  double get averageRating => (super.noSuchMethod(
        Invocation.getter(#averageRating),
        returnValue: 0.0,
      ) as double);

  @override
  _i3.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.JournalEntry>> fetchEntries() => (super.noSuchMethod(
        Invocation.method(
          #fetchEntries,
          [],
        ),
        returnValue:
            _i3.Future<List<_i4.JournalEntry>>.value(<_i4.JournalEntry>[]),
      ) as _i3.Future<List<_i4.JournalEntry>>);

  @override
  _i3.Future<void> createEntry(_i4.JournalEntry? entry) => (super.noSuchMethod(
        Invocation.method(
          #createEntry,
          [entry],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> refreshFromServer() => (super.noSuchMethod(
        Invocation.method(
          #refreshFromServer,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  void backgroundSync() => super.noSuchMethod(
        Invocation.method(
          #backgroundSync,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<void> deleteEntry(String? entryId) => (super.noSuchMethod(
        Invocation.method(
          #deleteEntry,
          [entryId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  List<_i4.JournalEntry> searchEntries(String? query) => (super.noSuchMethod(
        Invocation.method(
          #searchEntries,
          [query],
        ),
        returnValue: <_i4.JournalEntry>[],
      ) as List<_i4.JournalEntry>);

  @override
  _i3.Future<void> clearCache() => (super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> forceRefreshOnSignIn() => (super.noSuchMethod(
        Invocation.method(
          #forceRefreshOnSignIn,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
