// Mocks generated by Mockito 5.4.4 from annotations
// in GitaWisdom/test/screens/more_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:ui' as _i8;

import 'package:flutter/foundation.dart' as _i4;
import 'package:flutter/material.dart' as _i3;
import 'package:GitaWisdom/core/theme/theme_provider.dart' as _i12;
import 'package:GitaWisdom/models/simple_meditation.dart' as _i11;
import 'package:GitaWisdom/services/background_music_service.dart' as _i10;
import 'package:GitaWisdom/services/settings_service.dart' as _i9;
import 'package:GitaWisdom/services/supabase_auth_service.dart' as _i5;
import 'package:hive/hive.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBox_0<E> extends _i1.SmartFake implements _i2.Box<E> {
  _FakeBox_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeThemeData_1 extends _i1.SmartFake implements _i3.ThemeData {
  _FakeThemeData_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i4.DiagnosticLevel? minLevel = _i4.DiagnosticLevel.info}) =>
      super.toString();
}

/// A class which mocks [SupabaseAuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupabaseAuthService extends _i1.Mock
    implements _i5.SupabaseAuthService {
  MockSupabaseAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isAuthenticated => (super.noSuchMethod(
        Invocation.getter(#isAuthenticated),
        returnValue: false,
      ) as bool);

  @override
  bool get isAnonymous => (super.noSuchMethod(
        Invocation.getter(#isAnonymous),
        returnValue: false,
      ) as bool);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  String get databaseUserId => (super.noSuchMethod(
        Invocation.getter(#databaseUserId),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#databaseUserId),
        ),
      ) as String);

  @override
  _i7.Stream<bool> get authStateChanges => (super.noSuchMethod(
        Invocation.getter(#authStateChanges),
        returnValue: _i7.Stream<bool>.empty(),
      ) as _i7.Stream<bool>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i7.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<bool> signUpWithEmail(
    String? email,
    String? password,
    String? name,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUpWithEmail,
          [
            email,
            password,
            name,
          ],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> signInWithEmail(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithEmail,
          [
            email,
            password,
          ],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> signInAnonymously() => (super.noSuchMethod(
        Invocation.method(
          #signInAnonymously,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<bool> resetPassword(String? email) => (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [email],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> updatePassword(String? newPassword) => (super.noSuchMethod(
        Invocation.method(
          #updatePassword,
          [newPassword],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> verifyOTP(
    String? email,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyOTP,
          [
            email,
            token,
          ],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> deleteAccount() => (super.noSuchMethod(
        Invocation.method(
          #deleteAccount,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> checkUserExists(String? email) => (super.noSuchMethod(
        Invocation.method(
          #checkUserExists,
          [email],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  void clearError() => super.noSuchMethod(
        Invocation.method(
          #clearError,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<bool> continueAsAnonymous() => (super.noSuchMethod(
        Invocation.method(
          #continueAsAnonymous,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> signInWithGoogle() => (super.noSuchMethod(
        Invocation.method(
          #signInWithGoogle,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> signInWithApple() => (super.noSuchMethod(
        Invocation.method(
          #signInWithApple,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SettingsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsService extends _i1.Mock implements _i9.SettingsService {
  MockSettingsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Box<dynamic> get box => (super.noSuchMethod(
        Invocation.getter(#box),
        returnValue: _FakeBox_0<dynamic>(
          this,
          Invocation.getter(#box),
        ),
      ) as _i2.Box<dynamic>);

  @override
  bool get isDarkMode => (super.noSuchMethod(
        Invocation.getter(#isDarkMode),
        returnValue: false,
      ) as bool);

  @override
  set isDarkMode(bool? v) => super.noSuchMethod(
        Invocation.setter(
          #isDarkMode,
          v,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get language => (super.noSuchMethod(
        Invocation.getter(#language),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#language),
        ),
      ) as String);

  @override
  set language(String? v) => super.noSuchMethod(
        Invocation.setter(
          #language,
          v,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get fontSize => (super.noSuchMethod(
        Invocation.getter(#fontSize),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#fontSize),
        ),
      ) as String);

  @override
  set fontSize(String? v) => super.noSuchMethod(
        Invocation.setter(
          #fontSize,
          v,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.ThemeMode get themeMode => (super.noSuchMethod(
        Invocation.getter(#themeMode),
        returnValue: _i3.ThemeMode.system,
      ) as _i3.ThemeMode);

  @override
  bool get musicEnabled => (super.noSuchMethod(
        Invocation.getter(#musicEnabled),
        returnValue: false,
      ) as bool);

  @override
  set musicEnabled(bool? v) => super.noSuchMethod(
        Invocation.setter(
          #musicEnabled,
          v,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get textShadowEnabled => (super.noSuchMethod(
        Invocation.getter(#textShadowEnabled),
        returnValue: false,
      ) as bool);

  @override
  set textShadowEnabled(bool? v) => super.noSuchMethod(
        Invocation.setter(
          #textShadowEnabled,
          v,
        ),
        returnValueForMissingStub: null,
      );

  @override
  double get backgroundOpacity => (super.noSuchMethod(
        Invocation.getter(#backgroundOpacity),
        returnValue: 0.0,
      ) as double);

  @override
  set backgroundOpacity(double? v) => super.noSuchMethod(
        Invocation.setter(
          #backgroundOpacity,
          v,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get canRefreshCache => (super.noSuchMethod(
        Invocation.getter(#canRefreshCache),
        returnValue: false,
      ) as bool);

  @override
  int get daysUntilNextRefresh => (super.noSuchMethod(
        Invocation.getter(#daysUntilNextRefresh),
        returnValue: 0,
      ) as int);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setAppLanguage(String? langCode) => super.noSuchMethod(
        Invocation.method(
          #setAppLanguage,
          [langCode],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setTheme(_i3.ThemeMode? mode) => super.noSuchMethod(
        Invocation.method(
          #setTheme,
          [mode],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setFontSize(String? size) => super.noSuchMethod(
        Invocation.method(
          #setFontSize,
          [size],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setLastCacheRefreshDate(DateTime? date) => super.noSuchMethod(
        Invocation.method(
          #setLastCacheRefreshDate,
          [date],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [BackgroundMusicService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBackgroundMusicService extends _i1.Mock
    implements _i10.BackgroundMusicService {
  MockBackgroundMusicService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  bool get isEnabled => (super.noSuchMethod(
        Invocation.getter(#isEnabled),
        returnValue: false,
      ) as bool);

  @override
  bool get isPlaying => (super.noSuchMethod(
        Invocation.getter(#isPlaying),
        returnValue: false,
      ) as bool);

  @override
  double get volume => (super.noSuchMethod(
        Invocation.getter(#volume),
        returnValue: 0.0,
      ) as double);

  @override
  bool get isDucking => (super.noSuchMethod(
        Invocation.getter(#isDucking),
        returnValue: false,
      ) as bool);

  @override
  _i11.MusicTheme get currentTheme => (super.noSuchMethod(
        Invocation.getter(#currentTheme),
        returnValue: _i11.MusicTheme.meditation,
      ) as _i11.MusicTheme);

  @override
  List<_i11.MusicTheme> get availableThemes => (super.noSuchMethod(
        Invocation.getter(#availableThemes),
        returnValue: <_i11.MusicTheme>[],
      ) as List<_i11.MusicTheme>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i7.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> startMusic() => (super.noSuchMethod(
        Invocation.method(
          #startMusic,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> stopMusic() => (super.noSuchMethod(
        Invocation.method(
          #stopMusic,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> pauseMusic() => (super.noSuchMethod(
        Invocation.method(
          #pauseMusic,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> resumeMusic() => (super.noSuchMethod(
        Invocation.method(
          #resumeMusic,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> setEnabled(bool? enabled) => (super.noSuchMethod(
        Invocation.method(
          #setEnabled,
          [enabled],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> setVolume(double? volume) => (super.noSuchMethod(
        Invocation.method(
          #setVolume,
          [volume],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> duck() => (super.noSuchMethod(
        Invocation.method(
          #duck,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> unduck() => (super.noSuchMethod(
        Invocation.method(
          #unduck,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> setTheme(_i11.MusicTheme? theme) => (super.noSuchMethod(
        Invocation.method(
          #setTheme,
          [theme],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  String getThemeName(_i11.MusicTheme? theme) => (super.noSuchMethod(
        Invocation.method(
          #getThemeName,
          [theme],
        ),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #getThemeName,
            [theme],
          ),
        ),
      ) as String);

  @override
  _i7.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ThemeProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockThemeProvider extends _i1.Mock implements _i12.ThemeProvider {
  MockThemeProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isDark => (super.noSuchMethod(
        Invocation.getter(#isDark),
        returnValue: false,
      ) as bool);

  @override
  String get fontPref => (super.noSuchMethod(
        Invocation.getter(#fontPref),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#fontPref),
        ),
      ) as String);

  @override
  bool get shadowEnabled => (super.noSuchMethod(
        Invocation.getter(#shadowEnabled),
        returnValue: false,
      ) as bool);

  @override
  double get backgroundOpacity => (super.noSuchMethod(
        Invocation.getter(#backgroundOpacity),
        returnValue: 0.0,
      ) as double);

  @override
  double get textScale => (super.noSuchMethod(
        Invocation.getter(#textScale),
        returnValue: 0.0,
      ) as double);

  @override
  _i3.ThemeMode get themeMode => (super.noSuchMethod(
        Invocation.getter(#themeMode),
        returnValue: _i3.ThemeMode.system,
      ) as _i3.ThemeMode);

  @override
  _i3.ThemeData get lightTheme => (super.noSuchMethod(
        Invocation.getter(#lightTheme),
        returnValue: _FakeThemeData_1(
          this,
          Invocation.getter(#lightTheme),
        ),
      ) as _i3.ThemeData);

  @override
  _i3.ThemeData get darkTheme => (super.noSuchMethod(
        Invocation.getter(#darkTheme),
        returnValue: _FakeThemeData_1(
          this,
          Invocation.getter(#darkTheme),
        ),
      ) as _i3.ThemeData);

  @override
  _i3.ThemeData get currentTheme => (super.noSuchMethod(
        Invocation.getter(#currentTheme),
        returnValue: _FakeThemeData_1(
          this,
          Invocation.getter(#currentTheme),
        ),
      ) as _i3.ThemeData);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i7.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> updateTheme({
    bool? isDark,
    String? fontPref,
    bool? shadowEnabled,
    double? backgroundOpacity,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTheme,
          [],
          {
            #isDark: isDark,
            #fontPref: fontPref,
            #shadowEnabled: shadowEnabled,
            #backgroundOpacity: backgroundOpacity,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> toggleDarkMode() => (super.noSuchMethod(
        Invocation.method(
          #toggleDarkMode,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> setFontSize(String? size) => (super.noSuchMethod(
        Invocation.method(
          #setFontSize,
          [size],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> toggleShadow() => (super.noSuchMethod(
        Invocation.method(
          #toggleShadow,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> setBackgroundOpacity(double? opacity) => (super.noSuchMethod(
        Invocation.method(
          #setBackgroundOpacity,
          [opacity],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
