// Mocks generated by Mockito 5.4.4 from annotations
// in GitaWisdom/test/screens/scenarios_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i7;

import 'package:GitaWisdom/models/chapter.dart' as _i10;
import 'package:GitaWisdom/models/chapter_summary.dart' as _i9;
import 'package:GitaWisdom/models/journal_entry.dart' as _i11;
import 'package:GitaWisdom/models/scenario.dart' as _i6;
import 'package:GitaWisdom/models/verse.dart' as _i3;
import 'package:GitaWisdom/services/enhanced_supabase_service.dart' as _i8;
import 'package:GitaWisdom/services/intelligent_scenario_search.dart' as _i13;
import 'package:GitaWisdom/services/progressive_scenario_service.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i12;
import 'package:supabase_flutter/supabase_flutter.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSupabaseClient_0 extends _i1.SmartFake
    implements _i2.SupabaseClient {
  _FakeSupabaseClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVerse_1 extends _i1.SmartFake implements _i3.Verse {
  _FakeVerse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ScenarioServiceAdapter].
///
/// See the documentation for Mockito's code generation for more information.
class MockScenarioServiceAdapter extends _i1.Mock
    implements _i4.ScenarioServiceAdapter {
  MockScenarioServiceAdapter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get hasScenarios => (super.noSuchMethod(
        Invocation.getter(#hasScenarios),
        returnValue: false,
      ) as bool);

  @override
  int get scenarioCount => (super.noSuchMethod(
        Invocation.getter(#scenarioCount),
        returnValue: 0,
      ) as int);

  @override
  Map<String, dynamic> get loadingProgress => (super.noSuchMethod(
        Invocation.getter(#loadingProgress),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i5.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i6.Scenario>> getAllScenarios() => (super.noSuchMethod(
        Invocation.method(
          #getAllScenarios,
          [],
        ),
        returnValue: _i5.Future<List<_i6.Scenario>>.value(<_i6.Scenario>[]),
      ) as _i5.Future<List<_i6.Scenario>>);

  @override
  List<_i6.Scenario> searchScenarios(
    String? query, {
    int? maxResults,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchScenarios,
          [query],
          {#maxResults: maxResults},
        ),
        returnValue: <_i6.Scenario>[],
      ) as List<_i6.Scenario>);

  @override
  _i5.Future<void> refreshFromServer() => (super.noSuchMethod(
        Invocation.method(
          #refreshFromServer,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> backgroundSync({_i7.VoidCallback? onComplete}) =>
      (super.noSuchMethod(
        Invocation.method(
          #backgroundSync,
          [],
          {#onComplete: onComplete},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  List<_i6.Scenario> filterByChapter(int? chapterId) => (super.noSuchMethod(
        Invocation.method(
          #filterByChapter,
          [chapterId],
        ),
        returnValue: <_i6.Scenario>[],
      ) as List<_i6.Scenario>);

  @override
  _i5.Future<bool> hasNewScenariosAvailable() => (super.noSuchMethod(
        Invocation.method(
          #hasNewScenariosAvailable,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
}

/// A class which mocks [EnhancedSupabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockEnhancedSupabaseService extends _i1.Mock
    implements _i8.EnhancedSupabaseService {
  MockEnhancedSupabaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SupabaseClient get client => (super.noSuchMethod(
        Invocation.getter(#client),
        returnValue: _FakeSupabaseClient_0(
          this,
          Invocation.getter(#client),
        ),
      ) as _i2.SupabaseClient);

  @override
  _i5.Future<bool> testConnection() => (super.noSuchMethod(
        Invocation.method(
          #testConnection,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> initializeLanguages() => (super.noSuchMethod(
        Invocation.method(
          #initializeLanguages,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setCurrentLanguage(String? langCode) => (super.noSuchMethod(
        Invocation.method(
          #setCurrentLanguage,
          [langCode],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i9.ChapterSummary>> fetchChapterSummaries(
          [String? langCode]) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchChapterSummaries,
          [langCode],
        ),
        returnValue:
            _i5.Future<List<_i9.ChapterSummary>>.value(<_i9.ChapterSummary>[]),
      ) as _i5.Future<List<_i9.ChapterSummary>>);

  @override
  _i5.Future<_i10.Chapter?> fetchChapterById(
    int? chapterId, [
    String? langCode,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchChapterById,
          [
            chapterId,
            langCode,
          ],
        ),
        returnValue: _i5.Future<_i10.Chapter?>.value(),
      ) as _i5.Future<_i10.Chapter?>);

  @override
  _i5.Future<List<_i10.Chapter>> fetchAllChapters([String? langCode]) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchAllChapters,
          [langCode],
        ),
        returnValue: _i5.Future<List<_i10.Chapter>>.value(<_i10.Chapter>[]),
      ) as _i5.Future<List<_i10.Chapter>>);

  @override
  _i5.Future<List<_i6.Scenario>> fetchScenariosByChapter(
    int? chapterId, [
    String? langCode,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchScenariosByChapter,
          [
            chapterId,
            langCode,
          ],
        ),
        returnValue: _i5.Future<List<_i6.Scenario>>.value(<_i6.Scenario>[]),
      ) as _i5.Future<List<_i6.Scenario>>);

  @override
  _i5.Future<_i6.Scenario?> fetchScenarioById(
    int? scenarioId, [
    String? langCode,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchScenarioById,
          [
            scenarioId,
            langCode,
          ],
        ),
        returnValue: _i5.Future<_i6.Scenario?>.value(),
      ) as _i5.Future<_i6.Scenario?>);

  @override
  _i5.Future<List<_i6.Scenario>> searchScenarios(
    String? query, [
    String? langCode,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchScenarios,
          [
            query,
            langCode,
          ],
        ),
        returnValue: _i5.Future<List<_i6.Scenario>>.value(<_i6.Scenario>[]),
      ) as _i5.Future<List<_i6.Scenario>>);

  @override
  _i5.Future<List<_i6.Scenario>> fetchScenarios({
    int? limit = 2000,
    int? offset = 0,
    String? langCode,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchScenarios,
          [],
          {
            #limit: limit,
            #offset: offset,
            #langCode: langCode,
          },
        ),
        returnValue: _i5.Future<List<_i6.Scenario>>.value(<_i6.Scenario>[]),
      ) as _i5.Future<List<_i6.Scenario>>);

  @override
  _i5.Future<int> getScenarioCount() => (super.noSuchMethod(
        Invocation.method(
          #getScenarioCount,
          [],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<List<_i3.Verse>> fetchVersesByChapter(
    int? chapterId, [
    String? langCode,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchVersesByChapter,
          [
            chapterId,
            langCode,
          ],
        ),
        returnValue: _i5.Future<List<_i3.Verse>>.value(<_i3.Verse>[]),
      ) as _i5.Future<List<_i3.Verse>>);

  @override
  _i5.Future<_i3.Verse> fetchRandomVerseByChapter(
    int? chapterId, [
    String? langCode,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchRandomVerseByChapter,
          [
            chapterId,
            langCode,
          ],
        ),
        returnValue: _i5.Future<_i3.Verse>.value(_FakeVerse_1(
          this,
          Invocation.method(
            #fetchRandomVerseByChapter,
            [
              chapterId,
              langCode,
            ],
          ),
        )),
      ) as _i5.Future<_i3.Verse>);

  @override
  _i5.Future<_i6.Scenario?> fetchRandomScenario() => (super.noSuchMethod(
        Invocation.method(
          #fetchRandomScenario,
          [],
        ),
        returnValue: _i5.Future<_i6.Scenario?>.value(),
      ) as _i5.Future<_i6.Scenario?>);

  @override
  _i5.Future<int> fetchScenarioCount(int? chapterId) => (super.noSuchMethod(
        Invocation.method(
          #fetchScenarioCount,
          [chapterId],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<void> insertJournalEntry(_i11.JournalEntry? entry) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertJournalEntry,
          [entry],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteJournalEntry(String? entryId) => (super.noSuchMethod(
        Invocation.method(
          #deleteJournalEntry,
          [entryId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i11.JournalEntry>> fetchJournalEntries() =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchJournalEntries,
          [],
        ),
        returnValue:
            _i5.Future<List<_i11.JournalEntry>>.value(<_i11.JournalEntry>[]),
      ) as _i5.Future<List<_i11.JournalEntry>>);

  @override
  _i5.Future<void> insertFavorite(String? scenarioTitle) => (super.noSuchMethod(
        Invocation.method(
          #insertFavorite,
          [scenarioTitle],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> removeFavorite(String? scenarioTitle) => (super.noSuchMethod(
        Invocation.method(
          #removeFavorite,
          [scenarioTitle],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<String>> fetchFavorites() => (super.noSuchMethod(
        Invocation.method(
          #fetchFavorites,
          [],
        ),
        returnValue: _i5.Future<List<String>>.value(<String>[]),
      ) as _i5.Future<List<String>>);

  @override
  _i5.Future<Map<String, dynamic>> getTranslationCoverage([String? langCode]) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTranslationCoverage,
          [langCode],
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<bool> refreshTranslationViews() => (super.noSuchMethod(
        Invocation.method(
          #refreshTranslationViews,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  bool isLanguageSupported(String? langCode) => (super.noSuchMethod(
        Invocation.method(
          #isLanguageSupported,
          [langCode],
        ),
        returnValue: false,
      ) as bool);

  @override
  String getLanguageDisplayName(
    String? langCode, {
    bool? useNative = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLanguageDisplayName,
          [langCode],
          {#useNative: useNative},
        ),
        returnValue: _i12.dummyValue<String>(
          this,
          Invocation.method(
            #getLanguageDisplayName,
            [langCode],
            {#useNative: useNative},
          ),
        ),
      ) as String);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [IntelligentScenarioSearch].
///
/// See the documentation for Mockito's code generation for more information.
class MockIntelligentScenarioSearch extends _i1.Mock
    implements _i13.IntelligentScenarioSearch {
  MockIntelligentScenarioSearch() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i13.IntelligentSearchResult>> search(
    String? query, {
    int? maxResults = 10,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #search,
          [query],
          {#maxResults: maxResults},
        ),
        returnValue: _i5.Future<List<_i13.IntelligentSearchResult>>.value(
            <_i13.IntelligentSearchResult>[]),
      ) as _i5.Future<List<_i13.IntelligentSearchResult>>);

  @override
  _i5.Future<void> refreshMonthly() => (super.noSuchMethod(
        Invocation.method(
          #refreshMonthly,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
